DROP SCHEMA IF EXISTS MyWords;
CREATE SCHEMA MyWords;
USE MyWords;

CREATE TABLE User (
id BIGINT NOT NULL AUTO_INCREMENT,
Username VARCHAR(100) NOT NULL,
Password VARCHAR(100) NOT NULL,
PRIMARY KEY (UserId)
);

CREATE TABLE Phrase (
id BIGINT NOT NULL AUTO_INCREMENT,
Phrase VARCHAR(100) NOT NULL,
Definition VARCHAR(100) NOT NULL,
Note VARCHAR(100) NULL,
PRIMARY KEY (PhraseId)
);