DROP SCHEMA IF EXISTS MyWords;
CREATE SCHEMA MyWords;
USE MyWords;

CREATE TABLE User (
id BIGINT NOT NULL AUTO_INCREMENT,
Username VARCHAR(100) NOT NULL,
Password VARCHAR(100) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE Phrase (
id BIGINT NOT NULL AUTO_INCREMENT,
Phrase VARCHAR(100) NOT NULL,
Sentence VARCHAR(150) NOT NULL,
Definition VARCHAR(100) NOT NULL,
Note VARCHAR(100) NULL,
PRIMARY KEY (id)
);

INSERT INTO Phrase(Phrase,Sentence,Definition,Note) VALUES('Hello','Are you OK?','你好','');